version: "3.2"

services:
  web_gitea:
    image: gitea/gitea:latest
    env_file: 
      - gitea.env
    restart: always
    volumes:
      - "/home/git/data:/data"
    ports:
      - "3000:3000"
      - "2221:22"
    depends_on:
      - db_gitea
  db_gitea:
    image: mariadb:10
    restart: always
    env_file: 
      - db.env
    networks:
      - gitea
    volumes:
      - ./db/:/var/lib/mysql