version: "2"

services:
  web_gitea:
    image: gitea/gitea:latest
    env_file: 
      - gitea.env
    restart: always
    volumes:
      - "/home/git/data:/data"
    ports:
      - "3000:3000"
      - "2221:22"
