version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:

services:
  server:
    image: gitea/gitea:latest
    env_file: 
      - gitea.env
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    env_file: 
      - db.env
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql